// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grolwwxmzkndriodjvnq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdyb2x3d3htemtuZHJpb2Rqdm5xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMjYyODEsImV4cCI6MjA2ODYwMjI4MX0.PdJ9OdZty3QuMC4X6sBDiGdvjl9-B6ZWjvuU_rqTxIQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});